#'string search
#'@title baseline
#'@description string search.
#'
#' @param s first number
#' @param p second number
#'
#' @return match index
#'
#' @examples
#' require(Bruteforce)
#' s <- ("abc")
#' p <- ("b")
#' print(baseline("abc", "b"))
#'
#' @export
baseline = function(s, p){
  start_index = c()
  for (i in 1: (1 + nchar(s) - nchar(p))) {
    if (match(s, p, i)){
      start_index = append(start_index, i)
    }
  }
  return (start_index)
}

#' @title match
#' @description string match.
#'
#' @param s first number
#' @param p second number
#' @param i number
#'
#' @return match index
#'
#' @examples
#' require(Bruteforce)
#' s <- ("abc")
#' p <- ("b")
#' i <- 1
#' print(match("abc", "b", 1))
#'
#' @export
match = function(s, p, i){

  target_len = nchar(p)
  # print(target_len)
  index = 1
  while (index <= target_len){
    # print(substring(s, i, i))
    # print(substring(p, index, index))
    if (substring(s, i, i) != substring(p, index, index)){
      return (FALSE)
    }
    index = index + 1
    i = i + 1
  }
  return (TRUE)
}


#' @title rabin_karp
#' @param s first number
#' @param p second number
#'
#' @return match index
#'
#' @examples
#' require(Bruteforce)
#' s <- ("abc")
#' p <- ("b")
#' print(rabin_karp("abc", "b"))
#'
#' @export
rabin_karp <- function(s,p){
  ls <- charToRaw(s)
  lp <- charToRaw(p)

  pval <- 0
  for(i in 1:length(lp)){
    pval <- pval*10 + as.numeric(lp[i])
  }

  sval <- 0
  for(i in 1:length(lp)){
    sval <- sval*10 + as.numeric(ls[i])
  }

  start_index <- c()
  for(i in 1:(length(ls)-length(lp)+1)){
    if(sval==pval){
      if(all(lp==ls[i:(i+length(lp)-1)])){
        start_index <- append(start_index, i)
      }
    }
    sval <- (sval-as.numeric(ls[i])*10^(length(lp)-1))*10+as.numeric(ls[i+length(lp)])
  }

  if(length(start_index)==0){
    print("No Matched String Found")
  }
  else{
    return(start_index)
  }
}


#' @title buildNext
#' @param Query first number
#' @param len second number
#'
#' @return match index
#'
#' @export
buildNext <- function(Query, len){
  Next <- rep(0, len)
#' indexing Next
  now <- 1
#' current pos on Query
  pos <- 2
  while (pos <= len) {
    if (Query[pos] == Query[now]) {
#' If the current query char equals the char after the end of the
#' prefix of the previous query char, equals it
      Next[pos] <- Next[now]
    }
    else {
#' If the current query char does not equals the char after the
#' prefix of the previous query char, it should equal the current
#' Next index (now, large), and then the Next index now would go
#' back to its Next position.
      Next[pos] <- now
      while (now>=1 && (Query[pos] != Query[now])){
        now <- Next[now]
      }
    }
    now <- now + 1
    pos <- pos + 1
  }
  Next[pos] <- now
  return(Next)
}

#' @title KMPSearch
#' @param Query query string array
#' @param Target target string array
#' @param Next next array generated by buildNext
#'
#' @return KMPSearch
#'
#
#' @export
KMPSearch <- function(Query, Target, Next) {
  cur_T <- 1
  matchPoss <- c()
  cur_Q = 1
  while (cur_T <= length(Target)) {
    while (cur_Q <= length(Query) && cur_T <= length(Target)) {
      if (Query[cur_Q] != Target[cur_T]) {
        cur_Q <- Next[cur_Q]
        if (cur_Q==0) {
          cur_Q <- 1
          cur_T <- cur_T + 1
        }
      }
      else {
        cur_Q <- cur_Q + 1
        cur_T <- cur_T + 1
      }
    }
    if (cur_Q>length(Query)){
      matchPoss <- c(matchPoss, cur_T - cur_Q + 1)
    }
    cur_Q <- Next[cur_Q]
  }
  return(matchPoss)
}

#' @title KMP
#' @param Target target string array
#' @param Query query string array
#'
#' @return KMP
#'
#'
#' @export
KMP <- function(Target, Query) {
  if (length(Query)==1) {
    Query <- strsplit(Query, split="")[[1]]
  }
  if (length(Target)==1) {
    Target <- strsplit(Target, split="")[[1]]
  }
  Next <- buildNext(Query, length(Query))
  matchPoss <- KMPSearch(Query, Target, Next)
  return(matchPoss)
}
